<?php

/**
 * @file
 * Contains install and update functions for Session Limit.
 */

/**
 * Implements hook_uninstall().
 */
function session_limit_uninstall() {
  variable_del('session_limit_max');
  variable_del('session_limit_behaviour');
  variable_del('session_limit_masquerade_ignore');
  variable_del('session_limit_logged_out_message_severity');
  variable_del('session_limit_logged_out_message');
  db_query("DELETE FROM {variable} WHERE name LIKE 'session_limit_rid_%'");
}
